language: python
python:
  - 2.6
  - 2.7
script: python setup.py test
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.7
  - DJANGO=1.4.13
  - DJANGO=1.5.8
  - DJANGO=1.6.5
install:
  - pip install -q Django==$DJANGO
branches:
  only:
    - master
after_success:
  - coveralls
